name = "JCGELibrary"
uuid = "0291785c-4d3c-45ec-ba8e-d8f5428f97c2"
authors = ["Riccardo Boero <ribo@nilu.no>"]
version = "0.0.0"

[deps]
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JCGEBlocks = "e7e2410e-b632-4869-8943-8241db0dfb31"
JCGECalibrate = "52bcf1bb-5715-4bdb-b809-8ade53bb6205"
JCGECore = "9fb9d605-0ed3-4980-82c1-f0874844db5d"
JCGEKernel = "cc244198-1562-43f7-ad75-589e1d675269"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[sources]
JCGEBlocks = { path = "../JCGEBlocks" }
JCGECalibrate = { path = "../JCGECalibrate" }
JCGECore = { path = "../JCGECore" }
JCGEKernel = { path = "../JCGEKernel" }
