name = "StandardCGEExample"
uuid = "b6d5c8a7-f6c5-4ca2-90dc-1a9cfd9b4f0c"
authors = ["Riccardo Boero <ribo@nilu.no>"]
version = "0.0.0"

[deps]
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JCGEKernel = "cc244198-1562-43f7-ad75-589e1d675269"
JCGELibrary = "0291785c-4d3c-45ec-ba8e-d8f5428f97c2"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"

[sources]
JCGEKernel = { path = "../../packages/JCGEKernel" }
JCGELibrary = { path = "../../packages/JCGELibrary" }
