name = "JCGEExamples"
uuid = "0291785c-4d3c-45ec-ba8e-d8f5428f97c2"
version = "0.0.0"
authors = ["Riccardo Boero <ribo@nilu.no>"]

[deps]
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
JCGEBlocks = "e7e2410e-b632-4869-8943-8241db0dfb31"
JCGECalibrate = "52bcf1bb-5715-4bdb-b809-8ade53bb6205"
JCGECore = "9fb9d605-0ed3-4980-82c1-f0874844db5d"
JCGERuntime = "cc244198-1562-43f7-ad75-589e1d675269"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
PATHSolver = "f5f7c340-0bb3-5c69-969a-41884d311d1b"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[sources]
JCGEBlocks = {path = "../JCGEBlocks"}
JCGECalibrate = {path = "../JCGECalibrate"}
JCGECore = {path = "../JCGECore"}
JCGERuntime = {path = "../JCGERuntime"}

[compat]
PATHSolver = "1.7.9"
