name = "JCGEKernel"
uuid = "cc244198-1562-43f7-ad75-589e1d675269"
authors = ["Riccardo Boero <ribo@nilu.no>"]
version = "0.0.0"

[deps]
DualSignals = "8c2a5f8d-86a5-4c4a-8a7e-c82e7a175bfb"
JCGECore = "9fb9d605-0ed3-4980-82c1-f0874844db5d"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[sources]
JCGECore = { path = "../JCGECore" }
